- name: Update_and_upgrade_apt_packages
  hosts: all
  become: true
  tasks:
    - apt:
        upgrade: "yes"
        update_cache: "yes"

- name: Install_and_configure_mysql
  become: true
  hosts: db_hosts
  roles:
    - mysql

- name: Install_and_configure_web_server
  become: true
  hosts: web_hosts
  roles:
    - web_server

- name: Start_web_server
  become: true
  hosts: web_hosts
  environment:
    MYSQL_DATABASE_HOST: "{{ hostvars[groups['db_hosts'][0]].ansible_host }}"
  tasks:
    - shell: "FLASK_APP=/home/ubuntu/simple-webapp/app.py nohup flask run --host=0.0.0.0 &"

- name: Install NGINX and configure a simple reverse proxy in front of two web servers
  become: true
  hosts: lb_hosts
  collections:
    - nginxinc.nginx_core
  tasks:
    - name: Install NGINX
      ansible.builtin.include_role:
        name: nginx

    - name: Configure NGINX
      ansible.builtin.include_role:
        name: nginx_config
      vars:
        nginx_config_http_template_enable: true
        nginx_config_http_template:
          - template_file: http/default.conf.j2
            deployment_location: /etc/nginx/conf.d/default.conf
            config:
              upstreams:
                - name: upstr
                  least_conn: true
                  servers:
                    - address: 172.31.15.2:5000
                    - address: 3.128.201.75:5000
              servers:
                - core:
                    listen:
                      - port: 80
                    server_name: "{{ ansible_host }}"
                  log:
                    access:
                      - path: /var/log/nginx/access.log
                        format: main
                  locations:
                    - location: /
                      proxy:
                        pass: http://upstr/
                        set_header:
                          field: Host
                          value: $host
        nginx_config_html_demo_template_enable: true
        nginx_config_html_demo_template:
          - template_file: www/index.html.j2
            deployment_location: /usr/share/nginx/html/server_one.html
            web_server_name: Ansible NGINX collection - Server one
          - template_file: www/index.html.j2
            deployment_location: /usr/share/nginx/html/server_two.html
            web_server_name: Ansible NGINX collection - Server two

